export const RETRIEVE_EMPLOYEE="RETRIEVE_EMPLOYEE";
export const LOAD_EMPLOYEE="LOAD_EMPLOYEE";
export const DELETE_EMPLOYEE="DELETE_EMPLOYEE";
export const ADD_EMPLOYEE="ADD_EMPLOYEE";
export const EDIT_EMPLOYEE="EDIT_EMPLOYEE";
